//forecast
export const FETCH_FORECAST = "FETCH_FORECAST";

//loading
export const SET_LOADING = "SET_LOADING";
export const REMOVE_LOADING = "REMOVE_LOADING";

export const FETCH_FORECAST_LOADING = "FETCH_FORECAST_LOADING";
export const FETCH_FORECAST_FINISHED = "FETCH_FORECAST_FINISHED";

//Errors
export const INSERT_ERROR = "INSERT_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
